const MAX_PROCESSORS = parseInt(process.env.MAX_PROCESSORS, 10) || 4;
const PROCESSOR_REFRESH_INTERVAL = parseInt(process.env.PROCESSOR_REFRESH_INTERVAL, 10) || 5000;

export { MAX_PROCESSORS, PROCESSOR_REFRESH_INTERVAL };